### ISSUE TITLE
add_MARBL (compute): Support for prognostic Chl

### ISSUE THREAD

**Issue by mnlevy1981** [mnlevy1981/MOM6#57]
Another feature that is available in POP and desired in MOM

**Comment by klindsay28** [comment]
It looks like the point in MOM6 to couple MARBL Chl to MOM6 is
subroutine `get_chl_from_model` in file `tracer/MOM_tracer_flow_control.F90`.
MOM6 is looking for 3D Chl, so we'll need to add that as an output field in MARBL.
POP was using surface Chl from MARBL.

**Comment by mnlevy1981** [comment]
Created https://github.com/marbl-ecosys/MARBL/issues/417

**Comment by mnlevy1981** [comment]
This is supported as of 5c6fddd
