### ISSUE TITLE
add_MARBL: area correction should not be applied to Sa_co2prog and Sa_co2diag

### ISSUE THREAD

**Issue by klindsay28** [mnlevy1981/MOM6#79]
The `areacor` argument should not be passed to `state_getimport` for `Sa_co2prog` and `Sa_co2diag`, as these are state variables, not fluxes. This is in `config_src/drivers/nuopc_cap/mom_cap_methods.F90`

**Comment by klindsay28** [comment]
It looks like the `State_SetExport` call for `Faoo_fco2_ocn` also needs `areacor=mod2med_areacor`.

**Comment by mnlevy1981** [comment]
fixed all three variables in 5477f56b2
